### PR TITLE
STUD-5588: GHA migration

### PR DESCRIPTION
**Pull request by joewaters-wf**
## Purpose
- BTR is deprecating WK Build and Skynet functionality in 2H 2024

## Solution
- Remove Dockerfile and skynet.yaml
- Add GHA workflow to produce SBOM artifact on tag (see OSS [requirements](https://wiki.atl.workiva.net/display/CICD/CI-CD+for+Workiva%27s+Public+%28OSS%29+Repositories) from BTR)
- Add GHA workflow to run unit tests

## Semantic Versioning (check one)

- [x] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [ ] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- [ ] run the following related examples: **(fill in)**
- [ ] Other necessary steps needed to fully exercise the solution should be added here. **(fill in)**

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by waynepaffhausen-wk — APPROVED** [review]
QA +10 
- GHA Updates only
- Build Successfull
- Jobs pass and upload expected artifacts

**Comment by joewaters-wf** [comment]
@Workiva/release-management-p for merge

**Review by waynepaffhausen-wk — APPROVED** [review]
lgtm

**Comment by joewaters-wf** [comment]
QA +1
- only skynet removed in last commit

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
