### PR TITLE
RM-155955 Release v3.2.5

### PR DESCRIPTION
**Pull request by joecotton-wk**
## Purpose

Adding test report to skynet runs

## Solution

High level overview of what was done. This is the roadmap for those who are going to CR.

## Semantic Versioning (check one)

- [ ] The following were changed in a non-backward compatible way and requires a major version bump:
  - _[link to the breaking change in the diff]_
- [ ] Something public was added or changed in backward compatible way, this requires a minor version bump
- [x] No public changes nor new features (backwards-compatible refactor or bug fix), so this can be included in a patch
      release

## How to QA

- [ ] Make sure Skynet passes
- [ ] Make sure Skynet shows test passing / failing numbers (these might take up to five minutes to show up in Skynet)
- [ ] Make sure Skynet the test report as a test artifact

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by katherinebishop-wk** [comment]
QA+1 

- [x]  Make sure Skynet passes
- [x]  Make sure Skynet shows test passing / failing numbers (these might take up to five minutes to show up in Skynet)
- [x]  Make sure Skynet the test report as a test artifact

**Review by katherinebishop-wk — APPROVED** [review]
LGTM

**Comment by joecotton-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
